FROM python:3.11-slim 

WORKDIR /app
# Install FFmpeg and clean up

COPY requirements.txt .
ENV PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000
CMD ["fastapi", "run" ,"main.py"]






